// Generated by gencpp from file steering/steer.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_STEER_H
#define STEERING_MESSAGE_STEER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct steer_
{
  typedef steer_<ContainerAllocator> Type;

  steer_()
    : a(0.0)  {
    }
  steer_(const ContainerAllocator& _alloc)
    : a(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::steering::steer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::steer_<ContainerAllocator> const> ConstPtr;

}; // struct steer_

typedef ::steering::steer_<std::allocator<void> > steer;

typedef boost::shared_ptr< ::steering::steer > steerPtr;
typedef boost::shared_ptr< ::steering::steer const> steerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::steer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::steer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::steering::steer_<ContainerAllocator1> & lhs, const ::steering::steer_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::steering::steer_<ContainerAllocator1> & lhs, const ::steering::steer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::steer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::steer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::steer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::steer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::steer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::steer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a9a8ccf1ae2be3477477819c0d93b4e";
  }

  static const char* value(const ::steering::steer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a9a8ccf1ae2be34ULL;
  static const uint64_t static_value2 = 0x77477819c0d93b4eULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/steer";
  }

  static const char* value(const ::steering::steer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
;
  }

  static const char* value(const ::steering::steer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::steer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct steer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::steer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steering::steer_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_STEER_H
